### ISSUE TITLE
How to use Critic with custom policies?

### ISSUE THREAD

**Issue by perilstar** [FractalBoy/perl-language-server#100]
I have a directory containing perlcritic policies, and have been trying to figure out how to get PLS to notify Critic of them. Looking at the PLS code, it seems there's nowhere that policies are added to Critic. Is there another way to do this? If not, an implementation would be much appreciated.

**Comment by FractalBoy** [comment]
The way I got it to work for myself was to add a local lib to my perlbrew configuration, and I put the policy that I wrote in there. If the policy is available in your @INC, then it should pick it up. You just then need to add it to your .perlcriticrc.

**Comment by perilstar** [comment]
Do you know if this is possible with plenv?

**Comment by WhoIsSethDaniel** [comment]
> Do you know if this is possible with plenv?

With any `perl`, including perl's built with `plenv` you can set the `PERL5LIB` environment variable to have a path (or paths) to your custom code. If you look at `perldoc perlrun` in the `ENVIRONMENT` section it will talk a little about `PERL5LIB`.
See [here](https://metacpan.org/dist/perl/view/pod/perlrun.pod#ENVIRONMENT).  Just make certain that `PERL5LIB` is exported when and where `pls` is run.

**Comment by perilstar** [comment]
Closing this issue for now.
