### ISSUE TITLE
Thank you for making this

### ISSUE THREAD

**Issue by pragma-** [FractalBoy/perl-language-server#108]
This language server is fantastic. It works extremely well with Neovim.

In fact, I was so pleased and happy with this that I even made a quick and dirty YouTube video to show it off to my friends and colleagues when I praise it:  https://youtu.be/twPSC3sZguY

Thanks again! Feel free to close this issue at any time.

**Comment by FractalBoy** [comment]
Looks good, thanks!

Perhaps you would like to share it on [Reddit](https://www.reddit.com/r/perl/) or [Twitter](https://twitter.com/i/communities/1471579416216145924)?
