### ISSUE TITLE
Vscode Files

### ISSUE THREAD

**Issue by rocketdv** [FractalBoy/perl-language-server#125]
The VSCode extension creates a pls temp file each time a file is saved, clogs up the sidebar, and makes it jump around, which can get very distracting when working. It also clogs up the Git explorer. Maybe put them in a temp dir or something?

**Comment by FractalBoy** [comment]
You can ignore the files by adding this to your config:

    "files.exclude": {
        "**/.pls-tmp*": true,
    },

**Comment by rocketdv** [comment]
Wow, thank you!!!!! 🙏🏻
