### ISSUE TITLE
ENV check in BEGIN block causes an error in VSCode

### ISSUE THREAD

**Issue by pmielle** [FractalBoy/perl-language-server#126]
Hello,

Syntax check fails in VSCode when testing that `%ENV` contains an expected key _in the BEGIN block_. (the issue does _not_ arise outside of it)
e.g. with the "foo" key:

```
#!/usr/bin/env perl
use strict;
use warnings;

BEGIN {
    $ENV{foo} or die "nope";
#   ^^^^^^^^^^^^^^^^^^^^^^^^ <-- vscode shows an error: "nope _perl_"
}
```

(?) I've noticed that it does not report an error when the query key exists in the environment that is currently running pls (e.g. PATH)

Thank you for your work on PLS! Looking forward to reading from you about this issue, and I'd be happy to clarify if needed

**Comment by FractalBoy** [comment]
I don't think there's anything that I can do about this. You need to get VSCode to start with your desired environment. You can add this to your settings.json:

```json
"terminal.integrated.env.linux": {
    "foo": "bar"
}
```

You'll probably need to completely exit out of VSCode for it to take effect. You can also try adding this to your settings.json:

```json
"terminal.integrated.profiles.linux": {
    "bash": {
        "path": "bash",
        "icon": "terminal-bash",
        "args": [
            "-l"
        ]
    }
}
```

Then you can put whatever environment variable you need into your .bash_profile. Again, you'll need to completely exit and restart VSCode.

**Comment by pmielle** [comment]
update:  `-f ./foo or die` inside BEGIN also causes an error if a "foo" file does not exist

**Comment by pmielle** [comment]
Well, `-f "./foo" or die` in BEGIN is valid perl, even if the file does not exist when I write the code. PLS should not report any error, should it?

To be clear I am not talking about runtime errors, but rather red squiggly lines in VSCode as if there was a syntax error caught by the language server

(sorry if I am missing something obvious)

**Comment by FractalBoy** [comment]
Not quite, Perl syntax checking does not only check syntax errors, it checks if there are any errors during the compilation phase (syntax or otherwise). So if something `die`s in a BEGIN block (which runs at compilation time) then that will be an error shown by PLS. It couldn't complete compilation because there was a fatal error during compilation.

**Comment by rabbiveesh** [comment]
Just to add some more detail:
it's not POSSIBLE to actually syntax check perl unless you at least run the code partially, b/c code can change how things compile.

Take a look at [this script](https://github.com/jwilk-archive/perl-friday/blob/370f06913b6a1998cc82cb91ca40c2994a024f89/friday.pm) which is only valid syntax on fridays.

listen, it's the price to pay for the flexibility perl provides. I had to shuffle around some code of mine to fire later than the BEGIN stage to work around this.

**Comment by pmielle** [comment]
thank you very much for you comments, turns out it was my mistake then. My apologies and thank you for you time: at the very least I understand LS a bit better now
