### ISSUE TITLE
Couldn't start client Perl Language Server(VScode)

### ISSUE THREAD

**Issue by zhfff4869** [FractalBoy/perl-language-server#129]
[Error - 8:51:20 PM] Starting client failed
Launching server using command D:\developTools\Perl\strawberry-perl-5.24\perl\bin failed.

I have installed Perl Language Server by cpan successfully, and I can use perl in terminal too, my perl extension on vscode is 2.4.0, and my Perl Language Server is also 2.4.0.
I dont know why I can't use it.

**Comment by FractalBoy** [comment]
The path to pls must be the path to pls, not to the bin directory.

**Comment by FractalBoy** [comment]
Also, I wouldn't expect pls to work on Windows.
