### ISSUE TITLE
CentOS 7 Install issues on system Perl v5.16.3

### ISSUE THREAD

**Issue by westinn** [FractalBoy/perl-language-server#133]
I'd love to utilize this at my current companies dev environments but I'm running into issues installing this on CentOS 7 using the system Perl version `(v5.16.3)`.

Looking at CPAN, it seems like all the dependencies allow for lower versions but the main PLS page specifies `Perl: v5.26.0`.

Is there a way to lower the requirements? If not, I'm willing to see if I can contribute a bit.

Thanks!

**Comment by FractalBoy** [comment]
It's possible it works on lower versions, but I haven't tested. There may be newer features in use that were not introduced until later.

Are you not able to build a perl for development purposes, using something like perlbrew? You could still configure PLS to use your system perl for syntax checking, if necessary

**Comment by westinn** [comment]
I have tried, but honestly not as much as I maybe should have. Our environments are a bit messy so it's not as easy as I'd like it to be. Thank you for the response though, I'll see what I can manage with perlbrew.
