### ISSUE TITLE
Textwidth being ignored

### ISSUE THREAD

**Issue by voidzero** [FractalBoy/perl-language-server#137]
Hi, when I load perlpls in neovim, the textwidth option seems to be ignored. For example, when I set textwidth to 69 and write a comment, the line doesn't break, and when I enter gqip in normal mode, it also does not break the line.

Is there an option I can set to restore the default nvim behavior? There, even when textwidth is set to 0, gqip breaks the line and adds comment chars where needed.

**Comment by FractalBoy** [comment]
I don't use nvim so I don't really understand your issue. Maybe if you disable perltidy formatting or make your perltidy config jibe better with your nvim config, you'll get the desired behavior.

-l=n sets the max width of a line to n in perltidy. You can just add that to ~/.perltidyrc.

**Comment by voidzero** [comment]
Ah. Okay, thanks for your answer, in that case this issue is out of scope for this project. Thanks for the pointers, and I'll go ahead and close this bug.
