### ISSUE TITLE
Windows?

### ISSUE THREAD

**Issue by ashrasmun** [FractalBoy/perl-language-server#165]
Hello,

I'm trying to use this LSP on Windows, however `cpan PLS` / `cpanm PLS` hangs on testing. Is that a temporary issue for version `0.905` or is this tool not supported on Windows?

Thanks.

**Comment by FractalBoy** [comment]
I've only very briefly tried to get this to work on Windows but I don't think the CPAN libraries PLS uses work on Windows.

I would be happy to merge in changes that get this to work on Windows but I neither have the time nor the desire to deal with Windows idiosyncrasies.
