### ISSUE TITLE
Is there a way to disable perltidy on save? 

### ISSUE THREAD

**Issue by sdondley** [FractalBoy/perl-language-server#176]
I have an autosave plugin installed. Everything time I leave insert mode, perltidy fires which is an annoyance. I tried disabling perltidy in the config with:

              perltidy = {
                 enabled = false,
              },

But this has no effect. I don't see anything in the documentation about this.

**Comment by FractalBoy** [comment]
What editor are you using?

**Comment by sdondley** [comment]
I found the issue. It wasn't PLS, it was another plugin. I mistakenly assumed PLS handled this.
