### ISSUE TITLE
client: vsix pacakge doesn't contain build output

### ISSUE THREAD

**Issue by camtauxe** [FractalBoy/perl-language-server#34]
Loading the extension in VS Code results in the following log entry from the Extension Host:

```
[2021-06-24 09:10:58.410] [exthost] [error] Activating extension FractalBoy.pls failed due to an error:
[2021-06-24 09:10:58.410] [exthost] [error] Error: Cannot find module '/home/ctauxe/.vscode/extensions/fractalboy.pls-0.0.5/out/extension'
```

On closer inspection, I realized that the packaged extension, `pls-0.0.5.vsix` only contains the files `package.json` and `README.md` in its extension directory.

Here are the steps I took when building the client extension:

1. Clone repository and switch to `client` directory.
2. `npm install`
3. `vsce package` (I also tried installing packages through npm instead of yarn and using the `--no-yarn` flag for vsce, but same result).

Below is the output of `vsce ls --no-yarn`, also demonstrating that it only considers the `pacakge.json` and `README.md` files.

```
$ vsce ls --no-yarn
Executing prepublish script 'npm run vscode:prepublish'...

> pls@0.0.5 vscode:prepublish
> webpack --mode production

asset extension.js 255 KiB [compared for emit] [minimized] (name: main) 1 related asset
runtime modules 931 bytes 4 modules
modules by path ./node_modules/ 648 KiB
  modules by path ./node_modules/vscode-languageclient/ 337 KiB 75 modules
  modules by path ./node_modules/vscode-languageserver-protocol/ 79.5 KiB 22 modules
  modules by path ./node_modules/vscode-jsonrpc/ 118 KiB 16 modules
  modules by path ./node_modules/yallist/*.js 8.42 KiB
    ./node_modules/yallist/yallist.js 8.21 KiB [built] [code generated]
    ./node_modules/yallist/iterator.js 207 bytes [built] [code generated]
9 modules
webpack 5.1.0 compiled successfully in 5678 ms

package.json
README.md
```

**Comment by FractalBoy** [comment]
Fixed in 7087612b8fcccd89154b0622255862d4c403ff84
