### ISSUE TITLE
allow use of a different perl for syntax checking

### ISSUE THREAD

**Issue by FractalBoy** [FractalBoy/perl-language-server#38]
PLS forks a perl process for syntax checking, so a different perl installation/version could potentially be used.

Probably just need to implement something like `perl.perl` as a configuration item and use that instead of `$^X` when syntax checking, if it is configured.

This would allow PLS to continue to require new versions of Perl, but allow syntax checking of a project on an older version.

**Comment by marcelarie** [comment]
What binary can be used for syntax checking?

**Comment by FractalBoy** [comment]
It has to be a Perl interpreter binary, i.e. `perl`
