### ISSUE TITLE
Can't locate object method "file" via package "URI::_generic"

### ISSUE THREAD

**Issue by alaurie** [FractalBoy/perl-language-server#42]
Getting the below error on starting PLS when opening a perl file in VSCode

![image](https://user-images.githubusercontent.com/1402140/123900587-a6bdf000-d9ac-11eb-9d06-8c8a03e2b290.png)

**Comment by FractalBoy** [comment]
You only opened a single file, correct? PLS has only been tested opening a directory.

I suppose it should work, but the features would be a bit more limited.

**Comment by alaurie** [comment]
That was it. I was opening a single perl file rather than the folder.

**Comment by FractalBoy** [comment]
Reopening as I think this is probably worth fixing eventually.
