### ISSUE TITLE
Add license to the VSCode extension

### ISSUE THREAD

**Issue by stphnlyd** [FractalBoy/perl-language-server#46]
Now it has not a license https://marketplace.visualstudio.com/items?itemName=FractalBoy.pls

Could you please add a license like other extensions in VSCode marketplace do?

**Comment by FractalBoy** [comment]
Will do. Thanks for letting me know.

**Comment by FractalBoy** [comment]
Fixed in d247b8b00c6af1f4d5e043bdd884eeed5e588fbc
