### ISSUE TITLE
WSL 2 support

### ISSUE THREAD

**Issue by PanosBougas** [FractalBoy/perl-language-server#47]
Hello and thanks for making this extension/module

I have installed the PLS module to my WSL2 Ubuntu 20.04 without issues.

Although when I open a simple .pl file the output of the PLS says `error` without any specific message on what goes wrong.

Do you know what may have caused this output?

**Comment by PanosBougas** [comment]
Oh I think I found the issue. I had loaded multiple workspace folders and the extension can work only with one. Sorry about that

**Comment by FractalBoy** [comment]
I actually developed this mostly on WSL 2 so I would be very surprised if it didn't work.
