### ISSUE TITLE
Neovim  documentation

### ISSUE THREAD

**Issue by WhoIsSethDaniel** [FractalBoy/perl-language-server#48]
Hello, I use PLS very successfully with Neovim and I'd like to document how I do it.  Where would be the best place to add this? 
I just recently had out-of-the-box support for PLS in Neovim included (https://github.com/neovim/nvim-lspconfig/pull/1013).

**Comment by FractalBoy** [comment]
You could add it to the README.

**Comment by WhoIsSethDaniel** [comment]
Update README.md. PR #49

**Comment by WhoIsSethDaniel** [comment]
Neovim doc accepted
