### ISSUE TITLE
Crash in vscode without a workspace

### ISSUE THREAD

**Issue by mitchjacksontech** [FractalBoy/perl-language-server#54]
## Problem

When opening a perl file without having any defined workspace or workplace folders, PLS crashes.

## Steps to reproduce

```bash
# Create an empty perl file
touch test.pl

# Without vscode already running, open test.pl with vscode
code test.pl
```

Extension crashes with this error:

> Can't locate object method "file" via package "URI::_generic" at /Users/mjac/perl5/perlbrew/perls/perl-5.34.0/lib/site_perl/5.34.0/PLS/Server/Request/Initialize.pm line 36, <DATA> line 1.

My environment:

M1 macOS 11.3.1
Perl version: 5.34.0
PLS Version: 0.88
PLS VSCode extension version: 0.0.9
Vscode version: 1.58.2

## Workaround

This can be worked around by opening the enclosing folder of the file you want to edit instead of the file itself `code ./` instead of `code test.pl`

## Discussion

The issue is in this code within PLS::Server::Request::Initialize

```perl
    my $root_uri = $self->{params}{rootUri};
    my $path     = URI->new($root_uri);

    $PLS::Server::State::ROOT_PATH = $path->file;

    my $index = PLS::Parser::Index->new(root => $path->file);
```

`$self->{params}{rootUri}` is undef when opening files without a workspace folder open. You can see the same error message with this code, basically reproducing the same situation:

```perl
use URI;
my $bork = URI->new(undef);
print $bork->file;
```

I assume rootUri should be provided as the CWD of the opened file, e.g. `file:///Users/mjac` I dug around into the `$self->{params}` data structure, but didn't see anything that looked like a usable path to substitute when rootUri is undef.

**Comment by FractalBoy** [comment]
I think this is a duplicate of #42

**Comment by mitchjacksontech** [comment]
Sorry, yes, is the same issue
