### ISSUE TITLE
Constructing a IO::Async::Stream with an encoding-enabled handle may not read correctly

### ISSUE THREAD

**Issue by mitchjacksontech** [FractalBoy/perl-language-server#63]
This problem is an environment problem, not a pls problem. Creating issue in case the workaround is useful for anybody seeing the same warnings.

I have a project that relies on PERL_UNICODE=SDA in the environment. ([docs](https://perldoc.perl.org/perlrun#PERL_UNICODE)). This is equivalent to running `perl -CSDA`

Observing deprecation warnings related to PERL_UNICODE. This is accompanied by intermittent crashing of PLS within vscode. The warnings would be fatal in 5.30+

## The warnings:
```
Constructing a IO::Async::Stream with an encoding-enabled handle may not read correctly at /home/username/perl5/perlbrew/perls/perl-5.26.3/lib/site_perl/username.26.3/PLS/Server.pm line 142.
sysread() is deprecated on :utf8 handles. This will be a fatal error in Perl 5.30 at /home/username/perl5/perlbrew/perls/perl-5.26.3/lib/5.26.3/x86_64-linux/IO/Handle.pm line 468, <DATA> line 1.
syswrite() is deprecated on :utf8 handles. This will be a fatal error in Perl 5.30 at /home/username/perl5/perlbrew/perls/perl-5.26.3/lib/5.26.3/x86_64-linux/IO/Handle.pm line 481, <DATA> line 1.
```

The deprecation warning is easily reproduced at the shell by running `PERL_UNICODE=S pls`

## How this happens

* PLS::Server calls IO::Async::Stream->new_for_stdio()
* new_for_stdio() grabs \*STDIN and \*STDOUT
* PERL_UNICODE=S defaults those handles to binmode :utf8, havoc ensues

## Workaround

Nullify the PERL_UNICODE environment variable when running PLS, by setting `"perl.syntax.perl": "perl -C0"`

**Comment by FractalBoy** [comment]
Thanks for posting this! I'm going to close this, since there is no fix.
