### ISSUE TITLE
Please add your .vscode folder

### ISSUE THREAD

**Issue by stphnlyd** [FractalBoy/perl-language-server#64]
I was going to look at the Windows issue, but found this repo not have the .vscode dir and can't build the extension. Other extensions has .vscode in their repo, see, 

https://github.com/microsoft/vscode-cpptools/tree/main/Extension
https://github.com/microsoft/vscode-python

**Comment by FractalBoy** [comment]
I don't think you actually need that directory. Where did you have trouble building the extension?

### To build for debugging:

Run `yarn webpack-dev`

Click create a launch.json file:
![image](https://user-images.githubusercontent.com/2024233/130801791-c431f9af-1926-4ebb-a688-2a0be116c96d.png)

Click VS Code Extension Development:
![image](https://user-images.githubusercontent.com/2024233/130801891-8069d5c5-e34d-4c1a-816b-d1516dd95a2e.png)

In the JSON file, in the bottom right, click Add Configuration:
![image](https://user-images.githubusercontent.com/2024233/130802041-bbdf8f8d-3edf-4378-b29d-c58ccdbbeeb0.png)

Click VS Code Extension Development:
![image](https://user-images.githubusercontent.com/2024233/130802099-2cc36490-ceb8-4b37-b45b-51f422b65f08.png)

Save, then click launch.

### To build for distribution:

Run `vsce package`

**Comment by FractalBoy** [comment]
Closing due to lack of response
