### ISSUE TITLE
PLS stops responding in vscode

### ISSUE THREAD

**Issue by cblake777** [FractalBoy/perl-language-server#70]
I've gotten PLS up and running in a WSL Ubuntu image and things seem to be working perfectly fine at first. Unfortunately, it just stops working after a while.  Under the "Outline" section I just see a message saying "loading symbols" (or something of that sort), also, any previously open files that were working are now not, and display the same message. 

In my (limited) testing, it coincidentally appears to be related whatever indexing VS Code does when it is first launched. As I mentioned, we have a fairly large library, and when VS Code tries to index the files in the workspace, it takes a decent chunk of time (it's one of the reasons I've still stick with Sublime, it handles that indexing differently). The delay is most likely because it's a remote mount via SSHFS (we can't use the Remote-SSH extension because the hosts are too old to support it). I say all this because while the indexing of those files is happening, the "Go To File" option doesn't really return any results. During this time, any files I manually open via the file tree are able to have their symbols identified. However, after a bit, I notice that the indexing finished and I am able to make use of "Go to file", which appears to be when the symbols stop working. I don't know that the two events are actually related, it seemed to happen around the same time.

**Comment by FractalBoy** [comment]
Right now, my guess is that this has something to do with locking the index file over SSHFS. I suspect that it doesn't support locking (not really sure how you would accomplish such a thing over SSH)

**Comment by FractalBoy** [comment]
@cblake777 any luck with making that change, or are you still seeing the same issue?

**Comment by cblake777** [comment]
Yea, I believe it resolved it.  I did run into the issue one further time right after making the change, but since then I have not encountered it again.  I double checked all logging / output windows (there isn't one for PLS listed), and there was nothing. Overall, it seems to be running solid now.

**Comment by FractalBoy** [comment]
There should be an output window that logs every time files are indexed.

Regardless, since it's working for you, I'll close this and you can let me know if you have further issues.
