### ISSUE TITLE
Possibility to configure subdirectories that will be ignored by PLS

### ISSUE THREAD

**Issue by haeberlet** [FractalBoy/perl-language-server#75]
Hi, I do have some directories in my project where perl files are copied to during testing. They are hidden from VSCode (using  "files.exclude" option in .vscode/settings.json) and github (using .gitignore). However PLS scans them, and shows e.g. their content when choosing "go to definition" (See screenshot).
<img width="552" alt="Screen Shot 2021-11-10 at 16 51 59" src="https://user-images.githubusercontent.com/6690432/141147328-ff50721a-4792-478a-a79c-8eb4eaf9f4a5.png">

It would be nice to have a configuration option to hide certain directories also from PLS. 
Additionally there could be an option to respect the "files.exclude" option and .gitignore also for PLS.

**Comment by FractalBoy** [comment]
You can create a .plsignore file in your project root directory to ignore files or directories.
