### ISSUE TITLE
Workspace symbols not showing

### ISSUE THREAD

**Issue by cblake777** [FractalBoy/perl-language-server#76]
I see that version 0.897 has workspace symbol support (thanks!). I upgraded to it, attempted to view workspace symbols, and nothing is returned.  I assume I'm doing something wrong, any suggestions?

As I mentioned in another issue, I have no output logging for PLS (screenshot attached to show what I do have).  I verified that PLS is running because when I disable it, the outline / symbols in file stop functioning, so I do know that PLS is working.

![image](https://user-images.githubusercontent.com/391509/141368880-66e8f181-9769-4077-9215-cb9222f23b70.png)

Thanks!

**Comment by FractalBoy** [comment]
Workspace symbols completely rely on indexing, the outline/symbols do not, they are the result of parsing the current document.

Since you have nothing logged, it would seem that you are still unable to index anything.

**Comment by cblake777** [comment]
Interesting. I do see there is a ".pls-cache/index" file at the root of my workspace, and it does contain data (around 5M).  Anything else I should look for?

**Comment by FractalBoy** [comment]
What do you get if you dump out that file? It's in Storable format, so you would use Storable::retrieve to parse it and then something like Data::Dumper to view it. 

If it's 5M, then I'm assuming PLS is able to find your files, this is just to double check.

Might still be a locking issue. lsof or fuser on that file could give us some clues.

**Comment by cblake777** [comment]
I came back to things today, and all of a sudden the workspace symbols stuff is working.  I'm not sure if it was just taking a really long time to process files or what, but I can use the workspace symbols today.

**Comment by FractalBoy** [comment]
Do you see anything logged now?

**Comment by FractalBoy** [comment]
Alright, since this is resolved, I'm closing the issue.
