### ISSUE TITLE
Hackathons in 2022

### ISSUE THREAD

**Issue by djzort** [FractalBoy/perl-language-server#78]
I am uncertain what the best contact is for perl-language-server so I just thought i would create an issue.

We in the perl marketing committee would like to get this project involved in an IDE Hackathon in 2022 (see https://news.perlfoundation.org/post/hackothon-events-planning-2022)

Please comment on the above post and/or jump in to the marketing channel on The Perl Foundations Slack instance (perlfoundation dot slack dot com)

**Comment by FractalBoy** [comment]
What would being involved consist of, on my part?

I read the article, but I don't have access to the Slack. How would I obtain access?

**Comment by djzort** [comment]
it seems that perlfoundation slack is set to try to reduce spam by making it a members-invite-members type thing. I have just sent an invite to your gmail listed here on github

**Comment by FractalBoy** [comment]
Okay, I joined.
