### ISSUE TITLE
definition retrieval doesn't always retrieve definition of entire symbol

### ISSUE THREAD

**Issue by WhoIsSethDaniel** [FractalBoy/perl-language-server#83]
If I have something like this in my code:

use A::B::C::D::E;

If a textDocument/definition is sent to PLS with position.character = 7 and the line being whatever line the above is on, PLS will attempt to retrieve the definition for A::B. If it exists it will show A::B. if not, nothing happens.  If the position.character is 10 ('C') a similar thing will happen for A::B::C. If instead a textDocument/definition is sent to PLS with position.character = 16 ('E') the definition for A::B::C::D::E will be retrieved if it can be found.  

Should it not always attempt to retrieve A::B::C::D::E regardless of what the position.character value is (assuming the character falls between 'A' and 'E')?  

I've noticed this with different code bases so I don't think it's specific to my setup.

PLS: 0.898
Perl: 5.34.0

**Comment by WhoIsSethDaniel** [comment]
If I perform the above steps in reverse (start at character 16) everything works as I would expect. Presumably the index has something to do with this.  So for my example I'm assuming an empty index to start.

**Comment by WhoIsSethDaniel** [comment]
Perhaps this is how it's supposed to work, but it surprised me, if so.

**Comment by FractalBoy** [comment]
It might come down to personal preference on this. What if you have a lot of stuff in the A namespace and you want to switch from A::B to A::C. If your cursor is at B, I'd appreciate seeing things under A::

**Comment by WhoIsSethDaniel** [comment]
Fair enough. It does work very well once  you understand how it works.  Thanks.
