### ISSUE TITLE
Issues with certain directories

### ISSUE THREAD

**Issue by carlosfrodriguez** [FractalBoy/perl-language-server#85]
Hi @FractalBoy,

This might be related to #82...

* [2022-02-13 23:42:26] Indexing /Users/carlos/Library/Application Support/xbar/plugins/crcmdtools/lib/BaseCommand.pm...
With this file everything works well, Syntax, Perl Critic, Symbols, etc.

* [2022-02-13 23:43:38] Indexing /Users/carlos/Library/Application Support/xbar/plugins/crcmdtools/lib/Commands/MAS.pm...
But this file only shows symbols...  syntax errors, perl critic, perl tidy are totally missing, I was not able to catch any errors in VS code logs.

My workspace configuration looks as follows...

```js
{
    "folders": [
        {
            "path": "/Users/carlos/Library/Application Support/xbar/plugins"
        },
    ],
    "settings": {
        "perl.inc": [
            "/Users/carlos/Library/Application Support/xbar/plugins/crcmdtools/lib"
        ],
    }
}

```

Im not sure if the space in `Application Support` could be the culprit.

Just to mention in other directories even much more nested but without spaces in the path works well with syntax, critic and tidy.

**Comment by FractalBoy** [comment]
Both paths have a space in them so I'm not sure that is the culprit. Not sure what the problem could be. I'll think on it a little.

**Comment by FractalBoy** [comment]
@carlosfrodriguez are you still having this issue?

**Comment by carlosfrodriguez** [comment]
Hi @FractalBoy, I switched to [Perl Navigator](https://marketplace.visualstudio.com/items?itemName=bscan.perlnavigator). :-/ if no one else has this issue then you can close it.
