### ISSUE TITLE
revisit BBEdit compatibility

### ISSUE THREAD

**Issue by tjparnell** [FractalBoy/perl-language-server#86]
First of all, thank you for this project. It looks quite capable. I would love to get this to work with [BBEdit](https://www.barebones.com/products/bbedit/) following their [support notes](https://www.barebones.com/support/bbedit/lsp-notes.html). 

I know @mixio opened pull request  #66 and I've pulled that code and updated it to your current base. While the simple JJ logger in the PR certainly doesn't need to be in the final merge, it was actually quite useful in sorting out the traffic between client and server when comparing between BBEdit and Visual Studio Code. I'm attaching two logs from each (I've cleaned up the JSON for ease of visibility). The biggest difference is where and how the client is sending PLS specific configuration. 

Based on BBEdit's recommendations for [advanced configurations](https://www.barebones.com/support/bbedit/lsp-notes.html#advanced), I'm putting the PLS JSON configuration into a provided directory for `initializationOptions`, and this gets included in the initial client request. VSC, on the other hand, sends its PLS configuration under a completely separate, unlabeled request after server initialization and client acknowledgment.

Is there a way for PLS to process its configuration from the initial client request under `initializationOptions`? I've tried putting the PLS configuration under different JSON keys, but PLS is not recognizing anything. It doesn't appear that BBEdit has any mechanism for sending a second request with the PLS configuration.

[bbedit_log.txt](https://github.com/FractalBoy/perl-language-server/files/8111802/bbedit_log.txt)
[visual_studio_log.txt](https://github.com/FractalBoy/perl-language-server/files/8111803/visual_studio_log.txt)

**Comment by FractalBoy** [comment]
Based on the documentation you linked to, I think you'll need to do something like this:

```
"workspaceConfigurations":
{
    //  global configuration applied to all workspaces
    "*":
    {
        "perl":
        {
              // PLS settings go here
        }
    },
}
```

**Comment by tjparnell** [comment]
Thanks for the prompt reply. Yes, that works. I hadn't thought to insert an additional `"*"` level when playing with different combinations.

Your current version won't work (nicely) as is. When BBEdit quits, it leaves behind the spawned `perl` PLS instances. The additional `PLS::Server::Request::Shutdown` and `PLS::Server::Request::Exit` modules (and the associated changes) that @mixio included in #66 PR are still needed. Not sure if you want to work off that PR or let @mixio clean up the PR (just remove the `JJ` logging stuff and update). I don't want to credit for his work.

There are still lingering issues when working with multiple projects (`@INC` leaks over into other open projects), but that's a separate issue.

**Comment by FractalBoy** [comment]
I'd be happy to merge just those changes if they work in BBEdit. I will reply on BBEdit users to test whether it works.

Could you submit a PR with only the shutdown/exit changes? I would have merged them a long time ago but I have concerns with the other code included in that PR.

**Comment by mixio** [comment]
@tjparnell,

Please proceed to submit a PR in a palatable form and don't worry about credits.
I think this little enhancement could benefit both the Perl and BBEdit communities.
Thank you for your contribution and many thanks to @FractalBoy for this project.
