### ISSUE TITLE
Loading of user snippets in VSCode after file opening is not working

### ISSUE THREAD

**Issue by fliebe92** [FractalBoy/perl-language-server#91]
Hey there,

thanks a lot for this really nice VSCode extension, I love it! There is only one point which I dislike a lot:

* I'm opening up one single directory (a repository) in VSCode.
* I'm jumping to one specific line in my code and start to type a defined shortcut of a user snippet I do have.
* As usual, I expected that my user snippet is working fine, but currently it's not.
* I have to wait several seconds, maybe up to 30s, to have everything "loaded" and running fine (the snippet is working then).

Any idea what is going on there? If I'm going to disable the extensions, my user snippets are loaded without any delay.

Please, let me know if I could help with this.

Thanks!
Flo

**Comment by fliebe92** [comment]
Hey @FractalBoy, thanks for your quick answer!

Is it possible to execute this indexing operation as an async operation somehow? Currently it seems that some stuff is really blocked by this operation.

As already mentioned in my first post, if there is anything I could help with, please, let me know!

**Comment by FractalBoy** [comment]
It's already async, but anything that needs it will block until the index is ready.

**Comment by fliebe92** [comment]
> It's already async, but anything that needs it will block until the index is ready.

Is there any chance to get this improved? For me, the question is: Why the user snippets are blocked by PLS indexing operation?

**Comment by FractalBoy** [comment]
I may have been mistaken. I actually think that anything that needs it will just complete without the data from the index. I don't know why the user snippet would cause a problem. I'll have to create one for myself and see.

**Comment by FractalBoy** [comment]
I am unable to reproduce this. Here are the steps I took.

1. Created a user snippet
2. Deleted the cache (.pls_cache)
3. Restarted VSCode
4. I was able to use my snippet before the indexing finished.

Can you test this again and let me know if this is still an issue for you?

**Comment by FractalBoy** [comment]
@fliebe92 Is this still an issue for you?

**Comment by fliebe92** [comment]
> @fliebe92 Is this still an issue for you?

Nope, I am not using it anymore. Closed.
